ConferenceApp/Models/ConferenceType.cs
using System.ComponentModel.DataAnnotations;

namespace ConferenceApp.Models
{
    public enum ConferenceType
    {
        [Display(Name = "Warsztaty")]
        Workshop,
        [Display(Name = "Wykłady")]
        Lecture,
        [Display(Name = "Zdalnie")]
        Remote
    }
}

ConferenceApp/Models/ConferenceUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ConferenceApp.Models
{
    public class ConferenceUserViewModel
    {
        [Display(Name = "Imię")]
        public string FirstName { get; set; }
        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }
        public string Email { get; set; }
        
        [Display(Name = "Zdjęcie")]
        public string PhotoUrl { get; set; }

        [Display(Name = "Typ konferencji")]
        public ConferenceType? ConferenceType { get; set; }
    }
}

ConferenceApp/Models/ErrorViewModel.cs
using System;

namespace ConferenceApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConferenceApp/Models/RegisterConferenceUserViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace ConferenceApp.Models
{
    public class RegisterConferenceUserViewModel
    {
        [Required]
        [Display(Name = "Imię")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }
        public string Email { get; set; }
        [Display(Name = "Zdjęcie")]
        public IFormFile Photo { get; set; }

        [Required]
        [Display(Name = "Typ konferencji")]
        public ConferenceType? ConferenceType { get; set; }
    }
}

ConferenceApp/Controllers/ConferenceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using ConferenceApp.Models;
using DNTCaptcha.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace ConferenceApp.Controllers
{
    public class ConferenceController : Controller
    {
        private readonly IHostEnvironment _env;
        private static readonly List<ConferenceUserViewModel> ConferenceUsers = new();

        public ConferenceController(IHostEnvironment env)
        {
            _env = env;
        }

        public IActionResult Index()
        {
            return View(ConferenceUsers);
        }

        [HttpGet]
        public ViewResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateDNTCaptcha(
            ErrorMessage = "Prosze podać prawidłowy numer",
            CaptchaGeneratorLanguage = Language.English,
            CaptchaGeneratorDisplayMode = DisplayMode.ShowDigits)]
        public ActionResult Register(RegisterConferenceUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                if (model.Photo is not null)
                {
                    string uploadsFolder = Path.Combine(_env.ContentRootPath, "wwwroot/images");
                    uniqueFileName = $"{Guid.NewGuid()}_{model.Photo.FileName}";
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    using var fileStream = new FileStream(filePath, FileMode.Create);
                    model.Photo.CopyTo(fileStream);
                }

                var conferenceUserVm = new ConferenceUserViewModel
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    ConferenceType = model.ConferenceType,
                    PhotoUrl = model.Photo is not null ? $"~/images/{uniqueFileName}" : "",
                };

                ConferenceUsers.Add(conferenceUserVm);

                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

ConferenceApp/Controllers/HomeController.cs
using ConferenceApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ConferenceApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConferenceApp/Views/Conference/Index.cshtml
@model IEnumerable<ConferenceApp.Models.ConferenceUserViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Users</h1>

<p>
    <a asp-action="Register">Register New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConferenceType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ConferenceType)
            </td>
            <td style="width: 20%">
                <img class="card-img-top" src="@item.PhotoUrl" alt="" asp-append-version="true">
            </td>
        </tr>
    }
    </tbody>
</table>

ConferenceApp/Views/Conference/Register.cshtml
@model ConferenceApp.Models.RegisterConferenceUserViewModel

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>Conference User</h4>
<hr/>

<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-controller="Conference" asp-action="Register" method="post" asp-antiforgery="true">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control"/>
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control"/>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ConferenceType" class="control-label"></label>
                <select class="form-control" asp-for="ConferenceType" asp-items="@Html.GetEnumSelectList<ConferenceType>()">
                    <option value="">--Wybierz--</option>
                </select>
                <span asp-validation-for="ConferenceType" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <div class="custom-file">
                    <input multiple asp-for="Photo" class="form-control custom-file-input">
                    <label class="custom-file-label">Choose file...</label>
                </div>
            </div>

            <div asp-validation-summary="All" class="text-danger"></div>

            <dnt-captcha asp-captcha-generator-max="999999"
                         asp-captcha-generator-min="111111"
                         asp-captcha-generator-language="English"
                         asp-captcha-generator-display-mode="ShowDigits"
                         asp-use-relative-urls="true"
                         asp-placeholder="Enter Captcha"
                         asp-validation-error-message="Please enter the security code."
                         asp-font-name="Tahoma"
                         asp-font-size="20"
                         asp-fore-color="#333333"
                         asp-back-color="#ccc"
                         asp-text-box-class="text-box form-control"
                         asp-text-box-template="<span class='input-group-prepend'><span class='form-group-text'></span></span>{0}"
                         asp-validation-message-class="text-danger"
                         asp-refresh-button-class="fas fa-redo btn-sm"
                         asp-use-noise="false"/>

            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                const fileLabel = $(this).next('.custom-file-label');
                const files = $(this)[0].files;
                
                if (files.length > 1) {
                    fileLabel.html(files.length + ' files selected');
                }
                else if (files.length === 1) {
                    fileLabel.html(files[0].name);
                }
            });
        });
    </script>
}

ConferenceApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ConferenceApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ConferenceApp</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ConferenceApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Conference" asp-action="Register">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - ConferenceApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>